# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

main:
  - label: Beranda
    title: Portal PPDB - PPDB online praktis dan mudah
    link: /
    class: homepage
  - label: Alur
    title: Portal PPDB - Alur PPDB
    link: page/alur-ppdb  
  - label: Informasi
    submenu:
      - link: page/aturan-pelaksanaan  
        label: Aturan Pelaksanaan
      #  title: Portal PPDB - Alur PPDB
      - link: page/jadwal-pelaksanaan
        label: Jadwal Pelaksanaan
        # title: Portal PPDB - Jadwal PPDB
      - link: page/daya-tampung
        label: Daya Tampung
        # title: Portal PPDB - Jalur PPDB
      - link: page/hasil-seleksi
        label: Hasil Seleksi
      - link: page/sekolah-peserta
        label: Sekolah Peserta
      - link: page/siswa-pendaftar
        label: Siswa Pendaftar
  - label: Jalur
    title: Portal PPDB - Jalur PPDB
    link: page/jalur-ppdb  
  - label: Statistik Hasil
    title: Portal PPDB - Statistik Hasil PPDB
    link: page/statistik-hasil-ppdb  
      #  - link: http://127.0.0.1:8000/kontak
      #  label: Kontak
      #  title: Portal PPDB - Jadwal PPDB
      # - label: The Bolt site
      # link: https://boltcms.io
      # class: bolt-site
      # title: Visit the excellent Bolt website!

foo: bar
